name: Android Build

on: pull_request

jobs:
    bulid:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            - name: Set Up JDK
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            - name: Run Tests
              run: ./andorid/gradlew test

            - name: Build Project
              run: ./andorid/gradlew assemble