name: Android Build

on: pull_request

jobs:
    bulid:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set Up JDK
              uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '11'

            - name: Run Tests
              run: cd android && ./gradlew test

            - name: Build Project
              run: cd android && ./gradlew assemble